### ISSUE TITLE
Spell mistake in method name

### ISSUE THREAD

**Issue by Aman003** [Micky5991/EventAggregator#7]
https://github.com/Micky5991/EventAggregator/blob/3f8b3abd51228eb26314d6af25b17843c7e747a5/EventAggregator/Elements/Subscription.cs#L158

IsDataChangingEvent should be the write name of method as per clean code practice!

**Comment by Micky5991** [comment]
Sorry for the late response, thank you for that hint. I fixed it for the next release.

https://github.com/Micky5991/EventAggregator/commit/689353fc5868e9018a89392cdbbc6c741d074278
